## Exercícios de Data Wrangling com `collected_research_people.csv`

Desenvolva os seguintes exercícios utilizando técnicas de datawrangling apresentadas nas aulas anteriores. Verifique, considerando a base de dados collected_research_people, quais os campos trarão valor para cada cenário e quais as transformações de dados necessárias.

In [47]:
# Importando biblioteca
import pandas as pd
import numpy as np

In [48]:
# Definindo o df
df = pd.read_csv('collected_research_people.csv')
df.head()

,Unnamed: 0,Nome,Endereerço,Cidade,Estado,phone,anual_income,Estado Civil,AAge,n_filhos,Moradia,Food_restrictions,streaming,diariamente_sun blocker,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email
0,0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,1,Davi Lucca Pereira>,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,2,Sr. Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,3,Kaique Azevedo%,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [49]:
# Resumo estatístico incluindo colunas categóricas
print(df.describe(include='all'))

        Unnamed: 0                Nome               Endereerço    Cidade  \
count    37.000000                  37                       29        27
unique         NaN                  37                       29        25
top            NaN  Maria Clara Novaes  Rodovia de Silveira, 67  Carvalho
freq           NaN                   1                        1         2
mean     18.000000                 NaN                      NaN       NaN
std      10.824355                 NaN                      NaN       NaN
min       0.000000                 NaN                      NaN       NaN
25%       9.000000                 NaN                      NaN       NaN
50%      18.000000                 NaN                      NaN       NaN
75%      27.000000                 NaN                      NaN       NaN
max      36.000000                 NaN                      NaN       NaN

                    Estado            phone  anual_income Estado Civil  \
count                   24               25     25.000000           25
unique                  14               25           NaN            8
top     Mato Grosso do Sul  (011) 3908 5991           NaN   Divorciado
freq                     3                1           NaN            6
mean                   NaN              NaN  67570.640000          NaN
std                    NaN              NaN  20917.823198          NaN
min                    NaN              NaN  22826.000000          NaN
25%                    NaN              NaN  53295.000000          NaN
50%                    NaN              NaN  71448.000000          NaN
75%                    NaN              NaN  86445.000000          NaN
max                    NaN              NaN  95433.000000          NaN

             AAge   n_filhos  Moradia Food_restrictions   streaming  \
count   30.000000  22.000000       28                24          22
unique        NaN        NaN        4                 4           9
top           NaN        NaN  Quitada           Nenhuma  Globo Play
freq          NaN        NaN       11                 9           5
mean    44.633333   2.909091      NaN               NaN         NaN
std     16.356973   1.600866      NaN               NaN         NaN
min     18.000000   0.000000      NaN               NaN         NaN
25%     30.250000   2.000000      NaN               NaN         NaN
50%     42.500000   3.000000      NaN               NaN         NaN
75%     60.000000   4.000000      NaN               NaN         NaN
max     78.000000   5.000000      NaN               NaN         NaN

       diariamente_sun blocker Vai na Praia Mensalmente Faz Academia  \
count                       25                       29           21
unique                       2                        2            2
top                        Não                      Sim          Não
freq                        13                       18           11
mean                       NaN                      NaN          NaN
std                        NaN                      NaN          NaN
min                        NaN                      NaN          NaN
25%                        NaN                      NaN          NaN
50%                        NaN                      NaN          NaN
75%                        NaN                      NaN          NaN
max                        NaN                      NaN          NaN

       Compra e Lê Livros Todos os Anos  Quantidade de Livros Comprados  \
count                                23                       10.000000
unique                                2                             NaN
top                                 Sim                             NaN
freq                                 15                             NaN
mean                                NaN                        5.200000
std                                 NaN                        2.573368
min                                 NaN                        0.000000
25%                                 NaN                        5.000000
50%                                 NaN                        5.000000
75%                                 NaN                        6.000000
max                                 NaN                       10.000000

       Autor Favorito                           email
count              12                              37
unique             12                              37
top      Enzo Rezende  mariaclaranovaes285@gemeil.com
freq                1                               1
mean              NaN                             NaN
std               NaN                             NaN
min               NaN                             NaN
25%               NaN                             NaN
50%               NaN                             NaN
75%               NaN                             NaN
max               NaN                             NaN

In [50]:
# Remover coluna duplicada
df = df.drop(columns=['Unnamed: 0'])
df.head()

,Nome,Endereerço,Cidade,Estado,phone,anual_income,Estado Civil,AAge,n_filhos,Moradia,Food_restrictions,streaming,diariamente_sun blocker,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira>,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr. Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo%,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [51]:
# Renomear colunas
renomeando_colunas = {'Endereerço': 'Endereço',
                    'phone': 'Telefone',
                    'anual_income': 'Renda Anual',
                    'AAge': 'Idade',
                    'n_filhos': 'Número de Filhos',
                    'Food_restrictions': 'Restrição Alimentar',
                    'streaming': 'Streaming',
                    'diariamente_sun blocker': 'Uso diário protetor solar',
                    'email': 'E-mail'
                    }

df.rename(columns= renomeando_colunas, inplace=True)

df.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrição Alimentar,Streaming,Uso diário protetor solar,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,E-mail
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira>,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr. Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo%,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [52]:
# Remoção de caracteres especiais na coluna Nome

df.Nome = df['Nome'].str.replace(r'[^a-zA-Zà-úÀ-Ú ]', '', regex=True)
df.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrição Alimentar,Streaming,Uso diário protetor solar,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,E-mail
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [92]:
# Remoção de sufixos na coluna Nome

df_construtora['Nome'] = df_construtora['Nome'].str.replace(r'^(Sr|Sra|Dr|Dra|Srta)\s+', '', regex=True).str.strip()

df_construtora.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Vai na Praia Mensalmente,Faz Academia,E-mail,"Minha casa, Minha vida",Investimento
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Não,Sim,mariaclaranovaes285@gemeil.com,True,True
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,Não,Sim,daviluccapereira933@exemplo.com,True,False
2,Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,Não,NaN,srcaiocaldeira626@gemeil.com,True,True
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Não,Não,kaiqueazevedo731@rotmail.com,True,True
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,Sim,NaN,pedromoreira622@gemeil.com,True,True

In [53]:
# Remoção de caracteres especiais na coluna Telefone e substituindo por *

df['Telefone'] = df['Telefone'].str.replace(r'[^0-9()\+\s-]', '*', regex=True)
df

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrição Alimentar,Streaming,Uso diário protetor solar,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,E-mail
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0**8--***,53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com
5,Sra Ana Júlia Castro,"Parque Olivia da Mata, 32",Nogueira dos Dourados,Rondônia,+55 (084) 4591-2403,54503.0,Solteiro,29.0,NaN,Aluguel,NaN,Netflix e HBO,NaN,Sim,Não,Sim,5.0,Marcelo Melo,sraanajliacastro740@gemeil.com
6,Erick Carvalho,"Sítio Farias, 264",NaN,Amazonas,84 9687 5023,NaN,D,26.0,NaN,Quitada,Lactose,NaN,Não,Sim,NaN,Não,NaN,NaN,erickcarvalho519@rotmail.com
7,Sra Ana Sophia Vieira,"Esplanada de Mendes, 72",NaN,NaN,5*******7*,93976.0,NaN,50.0,4.0,Aluguel,Nenhuma,NaN,Não,Não,NaN,Não,NaN,NaN,sraanasophiavieira974@gemeil.com
8,Davi Nascimento,"Rua da Paz, 72",Duarte,NaN,+55 51 6868 3666,65384.0,Divorciado,60.0,2.0,Aluguel,Nenhuma,Crunchyroll,Não,Sim,Sim,NaN,NaN,NaN,dav4inascimento856@rotmail.com
9,Juan da Mota,Viela das Neves,NaN,Espírito Santo,NaN,NaN,Divorciado,NaN,4.0,Aluguel,Lactose,Nenhum,NaN,Sim,NaN,Não,NaN,NaN,juandamota291@gemeil.com
10,Stephany Pinto,"Residencial Breno Sales, 27",Fernandes do Oeste,NaN,NaN,NaN,NaN,65.0,5.0,NaN,Nenhuma,HBO,Sim,NaN,Sim,Não,NaN,NaN,stephanypinto486@rotmail.com
11,Joana Rezende,Recanto Oliveira,Caldeira,NaN,0900 093 9760,71627.0,Divorciado,63.0,2.0,Quitada,Lactose,Nenhum,Não,Sim,Não,Sim,5.0,NaN,joanarezende680@gemeil.com
12,Dra Letícia Ribeiro,"Quadra Campos, 40",Jesus Paulista,NaN,NaN,67068.0,C,22.0,NaN,NaN,Glúten,Disney Plus,Não,NaN,Sim,Sim,NaN,Lorena Lopes,draletciaribeiro370@rotmail.com
13,Beatriz Azevedo,NaN,Costela da Praia,Santa Catarina,81 2891-7504,86389.0,Solteiro,33.0,2.0,De favor,NaN,Todos,Sim,Sim,NaN,Sim,NaN,Isis Santos,beatrizazevedo858@gemeil.com
14,André Monteiro,NaN,Vieira do Amparo,NaN,***52***78,22826.0,NaN,NaN,NaN,Aluguel,Glúten,NaN,Não,Não,Sim,Sim,6.0,Nicolas Silveira,andrmonteiro689@gemeil.com
15,João Guilherme Porto,"Loteamento Lima, 619",Santos do Amparo,Mato Grosso do Sul,NaN,NaN,Solteiro,78.0,NaN,NaN,NaN,Netflix e Disney,NaN,Sim,Sim,Sim,NaN,Sr. Lucas Ribeiro,jooguilhermeporto349@exemplo.com
16,Augusto Rocha,"Ladeira Luana Pires, 177",Silveira de da Luz,NaN,41 5504 8546,95433.0,NaN,54.0,5.0,Quitada,Lactose e Glúten,NaN,Não,NaN,Não,Sim,3.0,Gabrielly da Mota,augustorocha201@gemeil.com
17,Srta Isabelly da Rocha,"Estação Olivia Dias, 777",Gonçalves do Oeste,NaN,84 2319-1532,NaN,Solteiro,NaN,1.0,Quitada,Lactose e Glúten,NaN,Sim,NaN,Não,Sim,NaN,Amanda da Mota,srtaisabellydarocha503@gemeil.com
18,Heloísa Santos,"Praia Paulo da Rocha, 5",Aragão,Paraíba,0800 612 6032,45809.0,V,26.0,NaN,NaN,Lactose e Glúten,NaN,NaN,Não,Não,NaN,NaN,NaN,helosasantos598@rotmail.com
19,Calebe Azevedo,"Parque Alves, 220",NaN,Rio Grande do Norte,NaN,NaN,S,NaN,NaN,Quitada,NaN,Globo Play,Não,Sim,NaN,NaN,NaN,NaN,calebeazevedo917@rotmail.com
20,Ana Alves,"Lago de Caldeira, 9",Caldeira,Paraíba,51 5882 5998,86973.0,D,18.0,NaN,NaN,NaN,NaN,Sim,Não,NaN,NaN,NaN,NaN,anaalves702@rotmail.com
21,Maria Fernanda Ribeiro,NaN,Gomes dos Dourados,Pará,NaN,48124.0,Viúvo,NaN,3.0,De favor,NaN,Nenhum,Não,Sim,Não,Sim,5.0,Manuela da Costa,mariafernandaribeiro421@exemplo.com
22,Samuel Jesus,"Condomínio Ribeiro, 55",NaN,Bahia,**)**-*5**,93085.0,Viúvo,52.0,NaN,Financiamento,Nenhuma,NaN,NaN,Sim,Sim,NaN,NaN,NaN,samueljesus456@gemeil.com
23,Beatriz Ramos,NaN,Fernandes,Tocantins,+55 (021) 4719 9862,71448.0,NaN,34.0,2.0,De favor,Nenhuma,Nenhum,Não,Sim,NaN,NaN,NaN,NaN,beatrizramos384@gemeil.com
24,Dr Davi Cunha,"Via de Correia, 17",Barbosa,Tocantins,(084) 0305 6725,36994.0,V,40.0,NaN,NaN,NaN,Disney Plus,Sim,NaN,Não,NaN,NaN,NaN,drdavicunha261@exemplo.com
25,Enrico Cavalcanti,Vale Barros,NaN,NaN,(011) 3410 5199,NaN,Solteiro,25.0,NaN,De favor,NaN,NaN,NaN,Sim,NaN,NaN,NaN,NaN,enricocavalcanti318@gemeil.com
26,Raquel Moura,"Passarela Luiza Araújo, 36",Pires de Teixeira,Pará,NaN,NaN,Viúvo,42.0,4.0,Quitada,Glúten,NaN,NaN,NaN,Não,Não,NaN,NaN,raquelmoura251@gemeil.com
27,Lorena Cardoso,NaN,Monteiro do Galho,Pernambuco,84 6014-5325,92410.0,Divorciado,39.0,0.0,Quitada,Glúten,NaN,Sim,Sim,Sim,NaN,NaN,NaN,lorenacardoso729@rotmail.com
28,Diogo Caldeira,"Vila Kaique da Paz, 76",Novaes,NaN,NaN,NaN,Casado,36.0,4.0,NaN,Nenhuma,Netflix,Sim,Sim,NaN,NaN,NaN,NaN,diogocaldeira718@gemeil.com
29,Maria Gonçalves,"Vale Nogueira, 342",Moraes do Galho,NaN,+55 71 7088-8329,NaN,NaN,47.0,NaN,Financiamento,Nenhuma,Todos,Sim,NaN,NaN,Sim,10.0,Sr. Luiz Fernando Vieira,mariagonalves175@gemeil.com
30,Isadora Cardoso,"Sítio Fernandes, 47",Castro,Bahia,NaN,50056.0,NaN,30.0,1.0,NaN,Lactose e Glúten,Globo Play,NaN,Sim,Sim,NaN,NaN,NaN,isadoracardoso853@gemeil.com
31,Igor Ferreira,"Quadra de da Mata, 49",NaN,NaN,21 0712-6859,77504.0,Divorciado,NaN,2.0,Aluguel,Lactose,HBO,NaN,Não,NaN,NaN,NaN,NaN,igorferreira546@exemplo.com
32,Sabrina Nunes,Quadra da Luz,Novaes da Mata,Pará,+55 51 2213 5603,56484.0,NaN,57.0,2.0,De favor,Lactose e Glúten,HBO,Sim,Sim,NaN,Sim,NaN,Ana Nascimento,sabrinanunes864@exemplo.com
33,Pedro Miguel Silva,"Residencial de Rodrigues, 97",NaN,Distrito Federal,8***9*****,88600.0,NaN,67.0,5.0,Quitada,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,pedromiguelsilva613@exemplo.com
34,Dra Clarice da Conceição,NaN,Cavalcanti do Campo,Amazonas,+55 51 8245 2336,NaN,Divorciado,31.0,NaN,NaN,NaN,NaN,Não,Sim,NaN,Sim,5.0,Emilly Peixoto,draclaricedaconceio834@gemeil.com
35,Daniel Rodrigues,"Loteamento Mendes, 72",Sales de Rodrigues,Mato Grosso,(061) 5002 3548,76000.0,D,64.0,3.0,Quitada,Nenhuma,Globo Play,Não,NaN,Não,Não,NaN,NaN,danielrodrigues211@gemeil.com
36,Isis Silva,"Vila da Mota, 6",da Luz da Prata,Rondônia,**2*938(**,61280.0,NaN,62.0,4.0,Financiamento,NaN,Crunchyroll,NaN,Não,Não,Não,NaN,NaN,isissilva623@exemplo.com

In [55]:
# Substituir valores com * no Telefone

df['Telefone'] = df['Telefone'].apply(lambda x: np.nan if '*' in str(x) else x)
df

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrição Alimentar,Streaming,Uso diário protetor solar,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,E-mail
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com
5,Sra Ana Júlia Castro,"Parque Olivia da Mata, 32",Nogueira dos Dourados,Rondônia,+55 (084) 4591-2403,54503.0,Solteiro,29.0,NaN,Aluguel,NaN,Netflix e HBO,NaN,Sim,Não,Sim,5.0,Marcelo Melo,sraanajliacastro740@gemeil.com
6,Erick Carvalho,"Sítio Farias, 264",NaN,Amazonas,84 9687 5023,NaN,D,26.0,NaN,Quitada,Lactose,NaN,Não,Sim,NaN,Não,NaN,NaN,erickcarvalho519@rotmail.com
7,Sra Ana Sophia Vieira,"Esplanada de Mendes, 72",NaN,NaN,NaN,93976.0,NaN,50.0,4.0,Aluguel,Nenhuma,NaN,Não,Não,NaN,Não,NaN,NaN,sraanasophiavieira974@gemeil.com
8,Davi Nascimento,"Rua da Paz, 72",Duarte,NaN,+55 51 6868 3666,65384.0,Divorciado,60.0,2.0,Aluguel,Nenhuma,Crunchyroll,Não,Sim,Sim,NaN,NaN,NaN,dav4inascimento856@rotmail.com
9,Juan da Mota,Viela das Neves,NaN,Espírito Santo,NaN,NaN,Divorciado,NaN,4.0,Aluguel,Lactose,Nenhum,NaN,Sim,NaN,Não,NaN,NaN,juandamota291@gemeil.com
10,Stephany Pinto,"Residencial Breno Sales, 27",Fernandes do Oeste,NaN,NaN,NaN,NaN,65.0,5.0,NaN,Nenhuma,HBO,Sim,NaN,Sim,Não,NaN,NaN,stephanypinto486@rotmail.com
11,Joana Rezende,Recanto Oliveira,Caldeira,NaN,0900 093 9760,71627.0,Divorciado,63.0,2.0,Quitada,Lactose,Nenhum,Não,Sim,Não,Sim,5.0,NaN,joanarezende680@gemeil.com
12,Dra Letícia Ribeiro,"Quadra Campos, 40",Jesus Paulista,NaN,NaN,67068.0,C,22.0,NaN,NaN,Glúten,Disney Plus,Não,NaN,Sim,Sim,NaN,Lorena Lopes,draletciaribeiro370@rotmail.com
13,Beatriz Azevedo,NaN,Costela da Praia,Santa Catarina,81 2891-7504,86389.0,Solteiro,33.0,2.0,De favor,NaN,Todos,Sim,Sim,NaN,Sim,NaN,Isis Santos,beatrizazevedo858@gemeil.com
14,André Monteiro,NaN,Vieira do Amparo,NaN,NaN,22826.0,NaN,NaN,NaN,Aluguel,Glúten,NaN,Não,Não,Sim,Sim,6.0,Nicolas Silveira,andrmonteiro689@gemeil.com
15,João Guilherme Porto,"Loteamento Lima, 619",Santos do Amparo,Mato Grosso do Sul,NaN,NaN,Solteiro,78.0,NaN,NaN,NaN,Netflix e Disney,NaN,Sim,Sim,Sim,NaN,Sr. Lucas Ribeiro,jooguilhermeporto349@exemplo.com
16,Augusto Rocha,"Ladeira Luana Pires, 177",Silveira de da Luz,NaN,41 5504 8546,95433.0,NaN,54.0,5.0,Quitada,Lactose e Glúten,NaN,Não,NaN,Não,Sim,3.0,Gabrielly da Mota,augustorocha201@gemeil.com
17,Srta Isabelly da Rocha,"Estação Olivia Dias, 777",Gonçalves do Oeste,NaN,84 2319-1532,NaN,Solteiro,NaN,1.0,Quitada,Lactose e Glúten,NaN,Sim,NaN,Não,Sim,NaN,Amanda da Mota,srtaisabellydarocha503@gemeil.com
18,Heloísa Santos,"Praia Paulo da Rocha, 5",Aragão,Paraíba,0800 612 6032,45809.0,V,26.0,NaN,NaN,Lactose e Glúten,NaN,NaN,Não,Não,NaN,NaN,NaN,helosasantos598@rotmail.com
19,Calebe Azevedo,"Parque Alves, 220",NaN,Rio Grande do Norte,NaN,NaN,S,NaN,NaN,Quitada,NaN,Globo Play,Não,Sim,NaN,NaN,NaN,NaN,calebeazevedo917@rotmail.com
20,Ana Alves,"Lago de Caldeira, 9",Caldeira,Paraíba,51 5882 5998,86973.0,D,18.0,NaN,NaN,NaN,NaN,Sim,Não,NaN,NaN,NaN,NaN,anaalves702@rotmail.com
21,Maria Fernanda Ribeiro,NaN,Gomes dos Dourados,Pará,NaN,48124.0,Viúvo,NaN,3.0,De favor,NaN,Nenhum,Não,Sim,Não,Sim,5.0,Manuela da Costa,mariafernandaribeiro421@exemplo.com
22,Samuel Jesus,"Condomínio Ribeiro, 55",NaN,Bahia,NaN,93085.0,Viúvo,52.0,NaN,Financiamento,Nenhuma,NaN,NaN,Sim,Sim,NaN,NaN,NaN,samueljesus456@gemeil.com
23,Beatriz Ramos,NaN,Fernandes,Tocantins,+55 (021) 4719 9862,71448.0,NaN,34.0,2.0,De favor,Nenhuma,Nenhum,Não,Sim,NaN,NaN,NaN,NaN,beatrizramos384@gemeil.com
24,Dr Davi Cunha,"Via de Correia, 17",Barbosa,Tocantins,(084) 0305 6725,36994.0,V,40.0,NaN,NaN,NaN,Disney Plus,Sim,NaN,Não,NaN,NaN,NaN,drdavicunha261@exemplo.com
25,Enrico Cavalcanti,Vale Barros,NaN,NaN,(011) 3410 5199,NaN,Solteiro,25.0,NaN,De favor,NaN,NaN,NaN,Sim,NaN,NaN,NaN,NaN,enricocavalcanti318@gemeil.com
26,Raquel Moura,"Passarela Luiza Araújo, 36",Pires de Teixeira,Pará,NaN,NaN,Viúvo,42.0,4.0,Quitada,Glúten,NaN,NaN,NaN,Não,Não,NaN,NaN,raquelmoura251@gemeil.com
27,Lorena Cardoso,NaN,Monteiro do Galho,Pernambuco,84 6014-5325,92410.0,Divorciado,39.0,0.0,Quitada,Glúten,NaN,Sim,Sim,Sim,NaN,NaN,NaN,lorenacardoso729@rotmail.com
28,Diogo Caldeira,"Vila Kaique da Paz, 76",Novaes,NaN,NaN,NaN,Casado,36.0,4.0,NaN,Nenhuma,Netflix,Sim,Sim,NaN,NaN,NaN,NaN,diogocaldeira718@gemeil.com
29,Maria Gonçalves,"Vale Nogueira, 342",Moraes do Galho,NaN,+55 71 7088-8329,NaN,NaN,47.0,NaN,Financiamento,Nenhuma,Todos,Sim,NaN,NaN,Sim,10.0,Sr. Luiz Fernando Vieira,mariagonalves175@gemeil.com
30,Isadora Cardoso,"Sítio Fernandes, 47",Castro,Bahia,NaN,50056.0,NaN,30.0,1.0,NaN,Lactose e Glúten,Globo Play,NaN,Sim,Sim,NaN,NaN,NaN,isadoracardoso853@gemeil.com
31,Igor Ferreira,"Quadra de da Mata, 49",NaN,NaN,21 0712-6859,77504.0,Divorciado,NaN,2.0,Aluguel,Lactose,HBO,NaN,Não,NaN,NaN,NaN,NaN,igorferreira546@exemplo.com
32,Sabrina Nunes,Quadra da Luz,Novaes da Mata,Pará,+55 51 2213 5603,56484.0,NaN,57.0,2.0,De favor,Lactose e Glúten,HBO,Sim,Sim,NaN,Sim,NaN,Ana Nascimento,sabrinanunes864@exemplo.com
33,Pedro Miguel Silva,"Residencial de Rodrigues, 97",NaN,Distrito Federal,NaN,88600.0,NaN,67.0,5.0,Quitada,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,pedromiguelsilva613@exemplo.com
34,Dra Clarice da Conceição,NaN,Cavalcanti do Campo,Amazonas,+55 51 8245 2336,NaN,Divorciado,31.0,NaN,NaN,NaN,NaN,Não,Sim,NaN,Sim,5.0,Emilly Peixoto,draclaricedaconceio834@gemeil.com
35,Daniel Rodrigues,"Loteamento Mendes, 72",Sales de Rodrigues,Mato Grosso,(061) 5002 3548,76000.0,D,64.0,3.0,Quitada,Nenhuma,Globo Play,Não,NaN,Não,Não,NaN,NaN,danielrodrigues211@gemeil.com
36,Isis Silva,"Vila da Mota, 6",da Luz da Prata,Rondônia,NaN,61280.0,NaN,62.0,4.0,Financiamento,NaN,Crunchyroll,NaN,Não,Não,Não,NaN,NaN,isissilva623@exemplo.com

In [60]:
# Padronizando a coluna Estado Civil

df['Estado Civil'].replace({
    'S': 'Solteiro',
    'C': 'Casado',
    'D': 'Divorciado',
    'V': 'Viúvo'}, 
    inplace = True)

df.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrição Alimentar,Streaming,Uso diário protetor solar,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,E-mail
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

### Cenário 1

A empresa Carri Construtora contratou a empresa que você trabalha para encontrar possíveis compradores para seus novos empreendimento, disponíveis pelo programa Minha casa, Minha vida. 
A empresa quer entender as necessidades dos clientes e quer informações como:
- Quais clientes devemos abordar?
- Esse cliente está em busca de investir em um imóvel ou comprar para moradia?
- Qual é a quantidade ideal de quartos para os imóveis com base no número de filhos dos clientes?

Se um cliente tem 0-1 filhos, oferecer imóveis com 2 quartos.
Se um cliente tem 2-3 filhos, oferecer imóveis com 3 quartos.
Se um cliente tem 4 ou mais filhos, oferecer imóveis com 4 quartos ou mais.


**Se renda anual < 104k, então pode participar do programa Minha casa, Minha vida**

In [66]:
# Salvando df apenas com dados que podem ser úteis para esse cenário 
drop_construtora = {
    'Restrição Alimentar',
    'Streaming',
    'Uso diário protetor solar',
    'Compra e Lê Livros Todos os Anos',
    'Quantidade de Livros Comprados',
    'Autor Favorito'}

df_construtora = df.drop(columns= drop_construtora)
df_construtora.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Vai na Praia Mensalmente,Faz Academia,E-mail
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Não,Sim,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,Não,Sim,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,Não,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Não,Não,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,Sim,NaN,pedromoreira622@gemeil.com

In [68]:
# Verificando Coluna de Renda Anual

df_construtora['Renda Anual'].describe([])

count       25.000000
mean     67570.640000
std      20917.823198
min      22826.000000
50%      71448.000000
max      95433.000000
Name: Renda Anual, dtype: float64

In [107]:
# Como a Renda Anual máxima é abaixo de 104k, todos podem participar do Minha casa, Minha vida
df_construtora['Minha casa, Minha vida'] = True
clientes_abordar = df_construtora[df_construtora['Minha casa, Minha vida'] == True]

print('Lista dos clientes que devem ser abordados pela construtora:')
print(clientes_abordar['Nome'])

Lista dos clientes que devem ser abordados pela construtora:
0         Maria Clara Novaes
1         Davi Lucca Pereira
2              Caio Caldeira
3             Kaique Azevedo
4              Pedro Moreira
5           Ana Júlia Castro
6             Erick Carvalho
7          Ana Sophia Vieira
8            Davi Nascimento
9               Juan da Mota
10            Stephany Pinto
11             Joana Rezende
12           Letícia Ribeiro
13           Beatriz Azevedo
14            André Monteiro
15      João Guilherme Porto
16             Augusto Rocha
17         Isabelly da Rocha
18            Heloísa Santos
19            Calebe Azevedo
20                 Ana Alves
21    Maria Fernanda Ribeiro
22              Samuel Jesus
23             Beatriz Ramos
24                Davi Cunha
25         Enrico Cavalcanti
26              Raquel Moura
27            Lorena Cardoso
28            Diogo Caldeira
29           Maria Gonçalves
30           Isadora Cardoso
31             Igor Ferreira
32             Sabrina Nunes
33        Pedro Miguel Silva
34      Clarice da Conceição
35          Daniel Rodrigues
36                Isis Silva
Name: Nome, dtype: object

In [108]:
# Quem já tem casa própria (financiamento ou quitada) está mais voltado para imóvel como investimento
# Do contrário, são imóveis para moradia

df_construtora['Finalidade do Imóvel'] = np.where((df_construtora.Moradia == 'Quitada')|(df_construtora.Moradia == 'Financiamento'), 'Investimento', 'Moradia')

In [111]:
# Esse cliente está em busca de investir em um imóvel ou comprar para moradia?

print('Lista dos clientes e finalidade do imóvel:')
print(df_construtora[['Nome', 'Finalidade do Imóvel']])

Lista dos clientes e finalidade do imóvel:
                      Nome Finalidade do Imóvel
0       Maria Clara Novaes         Investimento
1       Davi Lucca Pereira              Moradia
2            Caio Caldeira         Investimento
3           Kaique Azevedo         Investimento
4            Pedro Moreira         Investimento
5         Ana Júlia Castro              Moradia
6           Erick Carvalho         Investimento
7        Ana Sophia Vieira              Moradia
8          Davi Nascimento              Moradia
9             Juan da Mota              Moradia
10          Stephany Pinto              Moradia
11           Joana Rezende         Investimento
12         Letícia Ribeiro              Moradia
13         Beatriz Azevedo              Moradia
14          André Monteiro              Moradia
15    João Guilherme Porto              Moradia
16           Augusto Rocha         Investimento
17       Isabelly da Rocha         Investimento
18          Heloísa Santos              Moradia
19          Calebe Azevedo         Investimento
20               Ana Alves              Moradia
21  Maria Fernanda Ribeiro              Moradia
22            Samuel Jesus         Investimento
23           Beatriz Ramos              Moradia
24              Davi Cunha              Moradia
25       Enrico Cavalcanti              Moradia
26            Raquel Moura         Investimento
27          Lorena Cardoso         Investimento
28          Diogo Caldeira              Moradia
29         Maria Gonçalves         Investimento
30         Isadora Cardoso              Moradia
31           Igor Ferreira              Moradia
32           Sabrina Nunes              Moradia
33      Pedro Miguel Silva         Investimento
34    Clarice da Conceição              Moradia
35        Daniel Rodrigues         Investimento
36              Isis Silva         Investimento

In [112]:
# Definindo condições e valores correspondentes para o número de quartos 
condicoes = [
    (df_construtora['Número de Filhos'] <= 1),
    (df_construtora['Número de Filhos'] <= 3),
    (df_construtora['Número de Filhos'] >= 4)
]

valores = ['2', '3', '4 ou mais']

# Criando a nova coluna 'Número de Quartos'
df_construtora['Número de Quartos'] = np.select(condicoes, valores, default='Desconhecido')

In [114]:
# Qual a quantidade ideal de quartos para ofertar?

print('Lista dos clientes, finalidade do imóvel e número de quartos recomendados:\n')
print(df_construtora[['Nome', 'Finalidade do Imóvel', 'Número de Quartos']])

Lista dos clientes, finalidade do imóvel e número de quartos recomendados:

                      Nome Finalidade do Imóvel Número de Quartos
0       Maria Clara Novaes         Investimento      Desconhecido
1       Davi Lucca Pereira              Moradia                 2
2            Caio Caldeira         Investimento      Desconhecido
3           Kaique Azevedo         Investimento         4 ou mais
4            Pedro Moreira         Investimento         4 ou mais
5         Ana Júlia Castro              Moradia      Desconhecido
6           Erick Carvalho         Investimento      Desconhecido
7        Ana Sophia Vieira              Moradia         4 ou mais
8          Davi Nascimento              Moradia                 3
9             Juan da Mota              Moradia         4 ou mais
10          Stephany Pinto              Moradia         4 ou mais
11           Joana Rezende         Investimento                 3
12         Letícia Ribeiro              Moradia      Desconhecido
13         Beatriz Azevedo              Moradia                 3
14          André Monteiro              Moradia      Desconhecido
15    João Guilherme Porto              Moradia      Desconhecido
16           Augusto Rocha         Investimento         4 ou mais
17       Isabelly da Rocha         Investimento                 2
18          Heloísa Santos              Moradia      Desconhecido
19          Calebe Azevedo         Investimento      Desconhecido
20               Ana Alves              Moradia      Desconhecido
21  Maria Fernanda Ribeiro              Moradia                 3
22            Samuel Jesus         Investimento      Desconhecido
23           Beatriz Ramos              Moradia                 3
24              Davi Cunha              Moradia      Desconhecido
25       Enrico Cavalcanti              Moradia      Desconhecido
26            Raquel Moura         Investimento         4 ou mais
27          Lorena Cardoso         Investimento                 2
28          Diogo Caldeira              Moradia         4 ou mais
29         Maria Gonçalves         Investimento      Desconhecido
30         Isadora Cardoso              Moradia                 2
31           Igor Ferreira              Moradia                 3
32           Sabrina Nunes              Moradia                 3
33      Pedro Miguel Silva         Investimento         4 ou mais
34    Clarice da Conceição              Moradia      Desconhecido
35        Daniel Rodrigues         Investimento                 3
36              Isis Silva         Investimento         4 ou mais

### Cenário 2

Uma empresa chamada Hillo está estudando o mercado e quer encontrar uma parceria com uma empresa de Streaming (Netflix, Disney+, etc.), mas gostaria de saber quais as empresas dariam maior retorno de investimento. Eles podem fazer análise de machine learning também com esses dados.

In [119]:
# Salvando df apenas com dados que podem ser úteis para esse cenário 
drop_streaming = {
    'Moradia',
    'Restrição Alimentar',
    'Uso diário protetor solar',
    'Vai na Praia Mensalmente', 
    'Faz Academia',
    'Compra e Lê Livros Todos os Anos',
    'Quantidade de Livros Comprados',
    'Autor Favorito'}

df_streaming = df.drop(columns= drop_streaming)
df_streaming.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Streaming,E-mail
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Globo Play,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,Todos,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,NaN,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Globo Play,pedromoreira622@gemeil.com

In [121]:
# Substituindo o valor 'Todos'

df_streaming['Streaming'].replace({'Todos': 'Globo Play e Netflix e HBO e Disney Plus e Crunchyroll'}, inplace = True)

In [124]:
# Substituindo o valor 'Netflix e Disney'

df_streaming['Streaming'].replace({'Netflix e Disney': 'Netflix e Disney Plus'}, inplace = True)

In [127]:
# Como quer fazer análise de machine learning, devemos categorizar as colunas

df_streaming_categoria = df_streaming['Streaming'].str.get_dummies(sep = ' e ')

df_streaming = pd.concat([df_streaming, df_streaming_categoria], axis = 1)
df_streaming.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Streaming,...,Globo Play,HBO,Nenhum,Netflix,Crunchyroll,Disney Plus,Globo Play,HBO,Nenhum,Netflix
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Globo Play,...,1,0,0,0,0,0,1,0,0,0
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,Globo Play e Netflix e HBO e Disney Plus e Cru...,...,1,1,0,1,1,1,1,1,0,1
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,NaN,...,0,0,0,0,0,0,0,0,0,0
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Globo Play,...,1,0,0,0,0,0,1,0,0,0

In [128]:
# Excluindo a coluna de Streaming

df_streaming = df_streaming.drop(columns= 'Streaming')
df_streaming.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,E-mail,...,Globo Play,HBO,Nenhum,Netflix,Crunchyroll,Disney Plus,Globo Play,HBO,Nenhum,Netflix
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,mariaclaranovaes285@gemeil.com,...,1,0,0,0,0,0,1,0,0,0
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,daviluccapereira933@exemplo.com,...,1,1,0,1,1,1,1,1,0,1
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,srcaiocaldeira626@gemeil.com,...,0,0,0,0,0,0,0,0,0,0
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,kaiqueazevedo731@rotmail.com,...,0,0,0,0,0,0,0,0,0,0
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,pedromoreira622@gemeil.com,...,1,0,0,0,0,0,1,0,0,0

In [139]:
# Somando a quantidade total de usuários por Streaming
usuarios_streaming = df_streaming[['Crunchyroll','Disney Plus', 'Globo Play', 'HBO', 'Netflix']].sum()
usuarios_streaming

Crunchyroll    5
Disney Plus    6
Globo Play     8
HBO            7
Netflix        6
dtype: int64

In [141]:
# Qual empresa compensa fazer parceria? 

print(f'A empresa que compensa fazer parceria é {usuarios_streaming.idxmax()} com {usuarios_streaming.max()} usuários.')

A empresa que compensa fazer parceria é Globo Play com 8 usuários.

### Cenário 3

Uma influenciadora digital de bem-estar gostaria de analisar possíveis empreendimentos dentro das diferentes propostas que recebe. Ela está interessada em entender como as características demográficas e comportamentais de seu público podem influenciar as decisões sobre quais parcerias e projetos realizar.

Seu objetivo é identificar padrões e insights que a ajudem a decidir quais propostas são mais adequadas para seu público-alvo, considerando aspectos como a faixa etária, hábitos de consumo, atividades físicas, leitura, e questões de saúde como intolerância ao glúten e lactose.

- Qual é a idade média dos seguidores?
- Existe uma correlação entre a idade dos seguidores e o número de filhos?
- Quantos seguidores indicaram que fazem uso diário de protetor solar?
- Qual a porcentagem de seguidores que frequentam academia regularmente?
- Quantos seguidores têm restrições alimentares (glúten e/ou lactose)?
- Existe uma relação entre a frequência de ida à praia e o uso diário de protetor solar (se forem imputados os valores nulos)?
- Quantos seguidores indicaram que compram e leem livros anualmente?
- Qual a média de livros comprados por ano entre aqueles que indicaram leitura anual?

In [143]:
# Salvando df apenas com dados que podem ser úteis para esse cenário 
drop_influencer = {
    'Telefone', 
    'Renda Anual', 
    'Moradia',
    'Streaming'}

df_influencer = df.drop(columns= drop_influencer)
df_influencer.head()

,Nome,Endereço,Cidade,Estado,Estado Civil,Idade,Número de Filhos,Restrição Alimentar,Uso diário protetor solar,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,E-mail
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,NaN,43.0,NaN,Nenhuma,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,NaN,0.0,NaN,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,Solteiro,60.0,NaN,Lactose e Glúten,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,Casado,26.0,4.0,Lactose e Glúten,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,Casado,60.0,5.0,NaN,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [149]:
# Separando as restrições 
restricao = df_influencer['Restrição Alimentar'].str.get_dummies(sep = ' e ').drop(columns = ['Nenhuma'])

df_influencer = pd.concat([df_influencer, restricao], axis = 1)

In [152]:
# Excluindo a coluna de Restrições Alimentares

df_influencer = df_influencer.drop(columns= 'Restrição Alimentar')

KeyError: "['Restrição Alimentar'] not found in axis"

In [155]:
df_influencer.describe(include='all')

,Nome,Endereço,Cidade,Estado,Estado Civil,Idade,Número de Filhos,Uso diário protetor solar,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,E-mail,Glúten,Lactose
count,37,29,27,24,25,30.000000,22.000000,25,29,21,23,10.000000,12,37,37.000000,37.000000
unique,37,29,25,14,4,NaN,NaN,2,2,2,2,NaN,12,37,NaN,NaN
top,Maria Clara Novaes,"Rodovia de Silveira, 67",Carvalho,Mato Grosso do Sul,Divorciado,NaN,NaN,Não,Sim,Não,Sim,NaN,Enzo Rezende,mariaclaranovaes285@gemeil.com,NaN,NaN
freq,1,1,2,3,9,NaN,NaN,13,18,11,15,NaN,1,1,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,44.633333,2.909091,NaN,NaN,NaN,NaN,5.200000,NaN,NaN,0.297297,0.297297
std,NaN,NaN,NaN,NaN,NaN,16.356973,1.600866,NaN,NaN,NaN,NaN,2.573368,NaN,NaN,0.463373,0.463373
min,NaN,NaN,NaN,NaN,NaN,18.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,30.250000,2.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,NaN,42.500000,3.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,NaN,60.000000,4.000000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,1.000000,1.000000
max,NaN,NaN,NaN,NaN,NaN,78.000000,5.000000,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,1.000000,1.000000

In [156]:
# Qual é a idade média dos seguidores?
df_influencer['Idade'].mean()

44.63333333333333

In [159]:
# Existe uma correlação entre a idade dos seguidores e o número de filhos?
correlacao = df_influencer['Idade'].corr(df_influencer['Número de Filhos'])

print(correlacao)
print('Correlação Positiva Moderada: conforme a idade dos seguidores aumenta, o número de filhos também tende a aumentar, mas essa relação não é muito forte.')

0.3867702511176536
Correlação Positiva Moderada: conforme a idade dos seguidores aumenta, o número de filhos também tende a aumentar, mas essa relação não é muito forte.

In [160]:
# Quantos seguidores indicaram que fazem uso diário de protetor solar?
df_influencer['Uso diário protetor solar'].value_counts().get('Sim', 0)

12

In [162]:
# Qual a porcentagem de seguidores que frequentam academia regularmente?
frequenta_academia = df_influencer['Faz Academia'].value_counts(normalize=True).get('Sim', 0) * 100
print(f'Porcentagem de seguidores que frequentam academia regularmente: {frequenta_academia:.2f}%')

Porcentagem de seguidores que frequentam academia regularmente: 47.62%

In [164]:
# Quantos seguidores têm restrições alimentares (glúten e/ou lactose)?
restricao_gluten = df_influencer[df_influencer['Glúten'] == 1].shape[0]
restricao_lactose = df_influencer[df_influencer['Lactose'] == 1].shape[0]
restricao_ambas = df_influencer[(df_influencer['Glúten'] == 1) & (df_influencer['Lactose'] == 1)].shape[0]
total_restricoes = restricao_gluten + restricao_lactose - restricao_ambas

print(f"Número de seguidores com restrição a glúten: {restricao_gluten}")
print(f"Número de seguidores com restrição a lactose: {restricao_lactose}")
print(f"Número de seguidores com ambas as restrições (glúten e lactose): {restricao_ambas}")
print(f"Número total de seguidores com pelo menos uma restrição alimentar (glúten e/ou lactose): {total_restricoes}")

Número de seguidores com restrição a glúten: 11
Número de seguidores com restrição a lactose: 11
Número de seguidores com ambas as restrições (glúten e lactose): 7
Número total de seguidores com pelo menos uma restrição alimentar (glúten e/ou lactose): 15

In [166]:
# Existe uma relação entre a frequência de ida à praia e o uso diário de protetor solar (se forem imputados os valores nulos)?

df_influencer['Vai na Praia Mensalmente'].fillna(df_influencer['Vai na Praia Mensalmente'].mode()[0], inplace=True)
df_influencer['Uso diário protetor solar'].fillna(df_influencer['Uso diário protetor solar'].mode()[0], inplace=True)

relacao_praia_protetor = pd.crosstab(df_influencer['Vai na Praia Mensalmente'], df_influencer['Uso diário protetor solar'])

print("Relação entre Frequência de Ida à Praia e Uso Diário de Protetor Solar:")
print(relacao_praia_protetor.to_string())

Relação entre Frequência de Ida à Praia e Uso Diário de Protetor Solar:
Uso diário protetor solar  Não  Sim
Vai na Praia Mensalmente
Não                          8    3
Sim                         17    9

In [167]:
# Cálculo das proporções
total_nao_praia = relacao_praia_protetor.loc['Não'].sum()
total_sim_praia = relacao_praia_protetor.loc['Sim'].sum()

proporcao_nao_praia_sim = relacao_praia_protetor.loc['Não', 'Sim'] / total_nao_praia
proporcao_sim_praia_sim = relacao_praia_protetor.loc['Sim', 'Sim'] / total_sim_praia

print("\nProporção de Uso Diário de Protetor Solar:")
print(f"Para quem não vai à praia mensalmente: {proporcao_nao_praia_sim:.2%}")
print(f"Para quem vai à praia mensalmente: {proporcao_sim_praia_sim:.2%}")

Proporção de Uso Diário de Protetor Solar:
Para quem não vai à praia mensalmente: 27.27%
Para quem vai à praia mensalmente: 34.62%

In [168]:
# Quantos seguidores indicaram que compram e leem livros anualmente?
df_influencer['Compra e Lê Livros Todos os Anos'].value_counts().get('Sim', 0)

15

In [169]:
# Qual a média de livros comprados por ano entre aqueles que indicaram leitura anual?
df_influencer[df_influencer['Compra e Lê Livros Todos os Anos'] == 'Sim']['Quantidade de Livros Comprados'].mean()

5.2